name: Rust

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  IFS: $','

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: jitterbit/get-changed-files@v1
      id: abc
      with:
        format: csv
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Run rust
      run: |
        FILE=./skilltree-docs
        if [ -f "$FILE" ]; then
          exec $FILE
        else
          cargo build --release
          cp ./target/release/skilltree-docs ./
          git config --local user.name "MoreTacos"
          git add $FILE
          git commit -m "Adding executable file"
          rm -rf ./target
          exec $FILE
        fi
        
    - name: Send page curls
      run: echo ${{ steps.abc.outputs.added_modified }} | xargs -d , -I _ bash -c 'curl https://gymskilltree.com/insertpage?n=$(cut -f1 -d . <(basename _))'
        
    - name: Send page curls
      run: |
        for i in $(grep "packages" <(echo ${{ steps.abc.outputs.added_modified }})); do
           curl "https://gymskilltree.com/insert_package?p=$(basename $i '.svg')&n=$(basename $(dirname $i))";
        done
   
    - name: Push changes # push the output folder to your repo
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
