name: Rust

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: jitterbit/get-changed-files@v1
    - uses: docker://pandoc/core:2.9
      id: abc
      with:
        format: csv
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Send curl
      run: |
        git config --local user.name "MoreTacos"
        FILE=./sendcurl
        if [ ! -f "$FILE" ]; then
          cargo build --release
          cp ./target/release/sendcurl ./
          git add ./sendcurl
          git commit -m "Add sendcurl"
          rm -rf ./target
        fi
        ./sendcurl "${{ steps.abc.outputs.added_modified }}"
        
    - name: Create files
      run: |
        git config --local user.name "MoreTacos"
        FILE=./createfiles
        if [ ! -f "$FILE" ]; then
          cargo build --release
          cp ./target/release/createfiles ./
          git add $FILE
          git commit -m "Add createfiles"
          rm -rf ./target
        fi
        $FILE
        git add .
        git commit --allow-empty -m "Add pages"
   
    - name: Push changes # push the output folder to your repo
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
