name: Rust

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  IFS: $','

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: jitterbit/get-changed-files@v1
      id: abc
      with:
        format: csv
        token: ${{ secrets.GITHUB_TOKEN }}
  
    - name: Send out curls and update rust
      run: |
        sudo apt install curl
        FILE=./skilltree-docs
        if [ -f "$FILE" ]; then
          exec $FILE
        else 
          cargo build --release
          cp ./target/release/skilltree-docs ./
          git config --local user.name "MoreTacos"
          git add $FILE
          git commit -m "Adding executable file"
          exec $FILE
          rm -rf ./target
        fi
        
        for i in $(grep "pages" <(echo ${{ steps.abc.outputs.added_modified }})); do
           a=$(basename $i '.md')
           curl "https://gymskilltree.com/insert_page?n=$a"
        done
        for i in $(grep "packages" <(echo ${{ steps.abc.outputs.added_modified }})); do
           a=$(basename $i '.svg')
           b=$(basename $(dirname $i))
           curl "https://gymskilltree.com/insert_package?p=$a&n=$b"
        done
   
    - name: Push changes # push the output folder to your repo
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
